apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fe
    template:
        metadata:
            labels:
                app: fe
        spec:
            containers:
                - name: chatapp-frontend
                  image: maverick0809/chatapp-frontend
                  ports:
                      - containerPort: 80
                  resources:
                      limits:
                          cpu: '500m'
                          memory: '512Mi'
                      requests:
                          cpu: '250m'
                          memory: '256Mi'
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 80
                      periodSeconds: 10
                      initialDelaySeconds: 30
                      timeoutSeconds: 10
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                      periodSeconds: 10
                      initialDelaySeconds: 30
                      timeoutSeconds: 10
                      failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
    selector:
        app: fe
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
